### ISSUE TITLE
:align: center does not work for images

### ISSUE THREAD

**Issue by DavidPowell** [executablebooks/sphinx-book-theme#141]
**Describe the bug**

When using `:align: center` with images (SVG) from a jupyter-book document (myst source file), the image remains aligned to the left.

I am able to overcome this by adding the following to my custom.css:

```css
img.align-center {
   margin-left: auto;
   margin-right: auto;
   text-align:center;
   display:block;
}
```

I don't fully understand why this solution works, so I'm reluctant to submit it as a PR.

**Environment**
jupyter-book                   0.7.3
Sphinx                         2.4.4
sphinx-book-theme              0.0.33
sphinx-bootstrap-theme         0.7.1
sphinx-copybutton              0.2.11
sphinx-rtd-theme               0.4.3
sphinx-thebe                   0.0.7
sphinx-togglebutton            0.2.0
