### ISSUE TITLE
Thoughts on adding isort as a linter?

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-book-theme#149]
**Is your feature request related to a problem? Please describe.**

I like to sorted imports, for consistent code style.

**Describe the solution you'd like**

Add isort to the list of pre-commit linters, with `profile="black"` configuration.

**Describe alternatives you've considered**

Maintaining status quo, without consistent import styling. 😢 

**Additional context**

```yaml
- repo: https://github.com/timothycrosley/isort
  rev: 5.3.0 
  hooks:
  - id: isort
    args: [--format, black]
    files: \.py$
```
