### ISSUE TITLE
Make CSS easier to customize

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#183]
There are some common customization points that we might predict for this theme. In particular, things like background color, fonts/font-size, etc.

Other than specifically adding configuration for this, another thing we can do is choose reasonable CSS rules and provide documentation to easily override them.

An example where we are sub-optimal is in the background color of the page. If somebody changes the background color of the content, they get results like this:

![image](https://user-images.githubusercontent.com/1839645/90302230-9450cb80-de59-11ea-935d-ee4c4930efef.png)

Because we're manually setting the background of some other elements. We should figure out a way to over-ride this naturally (I wonder if there's some way we could let people over-ride with CSS variables?)

**Comment by choldgraf** [comment]
cc @bmcfee who may have some experience w/ this

**Comment by bmcfee** [comment]
> Other than specifically adding configuration for this, another thing we can do is choose reasonable CSS rules and provide documentation to easily override them.

:+1: to that!

For the record, here's my custom CSS file:

<details>

```css
/* Put your custom CSS here */
.left {
    margin: 5px 2px 2px 0px !important;
    float: left !important;
}

body { background-color: #fefefa;}
div.cell div.cell_input {
    background-color: #f7f7f3;
}


/*
colors = ['#0271AE', '#DC2830', '#FFC438',  # blue, red, light orange
            '#6E3B87', '#008D5D', '#FA902D',  # purple, green, orange
            '#0095B7', '#CB0C7B', '#F7E43C',  # cyan, magenta, yellow
            '#88B93B', '#444F95', '#F16232']  # pea green, dark blue, dark orange
*/
.blue {color: #0271AE;}
.red {color: #DC2830;}
.orange {color: #FFC438;}
.purple {color: #633B87;}
.green {color: #008D5D;}
.dkorange {color: #FA902D;}
.cyan {color: #0095B7;}
.magenta {color: #CB0C8B;}
.yellow {color: #F7E43C;}
.peagreen {color: #88B93B;}
.darkblue {color: #444F95;}
.darkorange {color: #F16232;}

div, h1, h2, h3, h4, h5, h6 {   
    font-family: "Palatino", serif; 
}

div.section {
    text-align: justify;
    text-justify: inter-word;
}

p.caption {
    text-align: justify;
    text-justify: inter-word;
}
span.caption-text {
    text-align: left;
    text-justify: auto;
}

/* Fixing up some pygments and code-styling CSS for accessibility */
code { font-size: 100%; color: #444F95; }
pre { font-family: monospace; }

/* .highlight { font-size: 125%; } */
.highlight .c1 { color: #633B87; }
.highlight .si { color: #633B87; }
.highlight .nn { color: #633B87; }
```

</details>

A quick summary of the changes I've made for my project:

- Wider main body
- Cosmetic changes to background colors and fonts (NBD)
- Text justification for captions and section headers (probably a good thing to put in sphinx-book-theme, but your call)
- Some custom color definitions to match my matplotlib theme
- Accessibility changes for code formatting

The last point is the kicker.  We have relatively strict accessibility requirements for NYU-hosted projects, and I've been using the [WCAG contrast checker plugin](https://addons.mozilla.org/en-US/firefox/addon/wcag-contrast-checker/) to validate book styling as I develop.  Most things are pretty good off the bat, but the pygments color scheme for code blocks fails hard.  This is really a problem for pygments, but I don't have much hope for getting a11y changes merged that far upstream in a timely fashion, hence the css hackery here.

The last batch of changes in my custom CSS overrides the pygments scheme to pass WCAG at AA status in both normal vision mode and deuteranomaly (the most common form of color-blindness).  Note that this is anecdotal, and I haven't tested it thoroughly beyond the examples in my project.  The resulting code style looks like this:

![image](https://user-images.githubusercontent.com/1190540/90319380-8ce6fc00-df05-11ea-86d0-95cea4d1e502.png)

I guess this is getting a little off topic, but I did want to document what changes I've been making to CSS here in case it helps inform what should be exposed and documented.

**Comment by chrisjsewell** [comment]
See https://github.com/executablebooks/sphinx-panels/blob/30a28b7acbd19fcccdba5417fa883cf3c0fdd2b4/sphinx_panels/__init__.py#L74-L82

**Comment by pradyunsg** [comment]
Furo is using CSS variables, which would be a good idea IMO. :)

**Comment by chrisjsewell** [comment]
> Furo is using CSS variables

Hence my link to where these are used/generated in sphinx-panels 😉

**Comment by choldgraf** [comment]
note that the pydata sphinx theme is also going to allow for CSS variable over-rides soon too: https://github.com/pandas-dev/pydata-sphinx-theme/pull/190

**Comment by rabernat** [comment]
We would love to use this theme for some Pangeo documentation sites, but we would like to customize it with our color theme and fonts (see https://github.com/pangeo-data/branding). Can someone point me to any examples of customized CSS with sphinx-book-theme?

**Comment by choldgraf** [comment]
@rabernat i think that @bmcfee did quite a bit of customization for his book, can't find a link to it right now though, maybe he has one

**Comment by bmcfee** [comment]
Here's the CSS file that I cooked up for my book (still not yet released, sorry...).

It basically covers some accessibility issues (checked with the WCAG plugin), particularly relating to code formatting, as well as some margin spacing and font preferences.  Dump this in `_static/content.css` and it should be good to go.

<details>
<summary>custom.css</summary>

```css
/* Put your custom CSS here */
.left {
    margin: 5px 2px 2px 0px !important;
    float: left !important;
}

body { background-color: #fefefa;}
div.cell div.cell_input {
    background-color: #f7f7f3;
}


/*
colors = ['#0271AE', '#DC2830', '#FFC438',  # blue, red, light orange
            '#6E3B87', '#008D5D', '#FA902D',  # purple, green, orange
            '#0095B7', '#CB0C7B', '#F7E43C',  # cyan, magenta, yellow
            '#88B93B', '#444F95', '#F16232']  # pea green, dark blue, dark orange
*/
.blue {color: #0271AE;}
.red {color: #DC2830;}
.orange {color: #FFC438;}
.purple {color: #633B87;}
.green {color: #008D5D;}
.dkorange {color: #FA902D;}
.cyan {color: #0095B7;}
.magenta {color: #CB0C8B;}
.yellow {color: #F7E43C;}
.peagreen {color: #88B93B;}
.darkblue {color: #444F95;}
.darkorange {color: #F16232;}

div, h1, h2, h3, h4, h5, h6 {   
    font-family: "Palatino", serif; 
}

div.section {
    text-align: justify;
    text-justify: inter-word;
}

p.caption {
    text-align: justify;
    text-justify: inter-word;
}
span.caption-text {
    text-align: left;
    text-justify: auto;
}

/* Fixing up some pygments and code-styling CSS for accessibility */
code { font-size: 100%; color: #444F95; }
pre { font-family: monospace; }

/* .highlight { font-size: 125%; } */
.highlight .c1 { color: #633B87; }
.highlight .si { color: #633B87; }
.highlight .nn { color: #633B87; }
```
</details>
