### ISSUE TITLE
Some texts are not translated in the html build

### ISSUE THREAD

**Issue by miguel-montes** [executablebooks/sphinx-book-theme#188]
When writing a book in another language (in my case is spanish), and with the correct language set in the sphinx section of _config.yml, some text appears in English.
Such is the case for the search box:
![image](https://user-images.githubusercontent.com/7091705/90676674-bcae4080-e232-11ea-985f-bce41a442047.png)
and the table of contents:
![image](https://user-images.githubusercontent.com/7091705/90676737-cd5eb680-e232-11ea-973d-b6cbc1b8ae4e.png)

The messages generated by sphinx, for instance after a search, are ok:
![image](https://user-images.githubusercontent.com/7091705/90676973-1a428d00-e233-11ea-84de-da18bb6daee7.png)

**To Reproduce**

1. Create a book
2. Set the language to spanish
3. Build the book

**Expected behavior**

All english messages are translated.

**Environment**

- Python 3.8.3
- Jupyter Book: 0.7.4
- MyST-NB: 0.8.5
- Sphinx Book Theme: 0.0.35
- MyST-Parser: 0.9.1
- Jupyter-Cache: 0.3.0
- Operating System: Ubuntu 20.04

**Additional context**

Sphinx configuration section in _config.yml

```
sphinx:
  config:
    latex_elements: 
      fncychap: \usepackage[Glenn]{fncychap}
      babel: \usepackage[spanish]{babel}
    language: "es"
```
