### ISSUE TITLE
Anchors are shaded by the fixed header bar. We need an offset.

### ISSUE THREAD

**Issue by hankcs** [executablebooks/sphinx-book-theme#270]
**Describe the bug**

When click a href refering to an anchor, that anchor will be shaded by the fixed header bar. I can't say it's 100% a bug, but definitely something degrades the user experience.

**To Reproduce**

I have an online document with this issue. Please visit this page at: https://hanlp.hankcs.com/docs/api/hanlp/utils/io_util.html#hanlp.utils.io_util.get_resource

It's genrated using sphinx-book-theme and ordinary sphinx syntax.

**Expected behavior**

I expect to see the `get_resource` method. But it is covered by the header.

**Environment**

- Python Version [e.g. 3.7.1]: Python 3.6.6
- Package versions or output of `jupyter-book --version`:0.8.3
- Operating System: macOS

**Additional context**

I've read [a stackoverflow thread](https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header) introducing an offset trick in css which might solve this issue. I don't know where is the best place to apply this trick so hope the upstream can work together to solve it.

Thanks.

**Comment by Naereen** [comment]
The anchors for the titles h1/h2/ etc works fine because of this CSS:
```css
.header-style::before, h1::before, h2::before, h3::before, h4::before, h5::before, h6::before {
    display: block;
    content: "";
    height: 80px;
    margin: -80px 0 0;
}
```
And indeed when inspecting the a (recent) Sphinx webpage you can see a virtual blank space before the header:
![Capture d’écran_2021-02-09_19-02-59](https://user-images.githubusercontent.com/11994719/107407092-84b0f780-6b09-11eb-8315-42afd5ea4584.png)

Solving this issue should just be a matter of doing the same thing but for `dt::before`:
```css
dt::before {
    display: block;
    content: "";
    height: 50px;
    margin: -50px 0 0;
}
```
See the fixed behavior on this GIF: (it takes a few seconds, I first show the bug, then activate this hack, then show the fixed bug)
![Peek 09-02-2021 19-07](https://user-images.githubusercontent.com/11994719/107407640-33553800-6b0a-11eb-9516-49ff441a5326.gif)

If someone can tell me which CSS file here should contain this additional behavior, I can edit them and submit a PR.

Oh, I also think that it should concern more anchors, not just dt (used for Glossary pages), like the example given above.
