### ISSUE TITLE
Improve CSS for `topic` directive

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/sphinx-book-theme#277]
the top directive CSS is a bit lacklustre, coming directly from bootstrap:

```css
.topic {
 background-color:#eee
}
```

<img width="841" alt="image" src="https://user-images.githubusercontent.com/2997570/105241746-d3e8b580-5b65-11eb-9656-21febba2b4c8.png">

this is the source and rendered:

````
```{topic} Something
body
```
````

```html
<div class="topic">
<p class="topic-title">Something</p>
<p>body</p>
</div>
```

**Comment by chrisjsewell** [comment]
Note that frontmatter containing a dedication and/or abstract key

rst
```restructuredtext
:dedication: To my *homies*
:abstract: Something something **dark** side

The MyST Syntax Guide
=====================
```

myst
```yaml
---
dedication: |
    To my *homies*
abstract: Something something **dark** side
---

# The MyST Syntax Guide
```

leads to:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/2997570/105244238-23c87c00-5b68-11eb-9833-8d69605e34a1.png">

```html
<div class="dedication topic">
<p class="topic-title">Dedication</p>
<p>To my <em>homies</em>
</p>
</div>
<div class="abstract topic">
<p class="topic-title">Abstract</p>
<p>Something something <strong>dark</strong> side</p>
</div>
```

we might consider doing something special with these
