### ISSUE TITLE
Document Algolia DocSearch integration

### ISSUE THREAD

**Issue by hammer** [executablebooks/sphinx-book-theme#394]
### Description / Summary

I would like to use Algolia's [DocSearch](https://docsearch.algolia.com/) to get fast typeahead on our search box. There are instructions for how to integrate DocSearch with the RTD theme at https://github.com/readthedocs/sphinx_rtd_theme/issues/761. I have tried to modify the CSS/JS for this theme but I can't make it work.

### Value / benefit

This would allow users of this theme to have fast typeahead on their search box.

### Implementation details

I have tried using `inputSelector: '#search-input'` in the JS and `#search-input { overflow: visible; }` in the CSS, but this does not work.

**Comment by hammer** [comment]
I noticed while investigating this issue that the `#search-input` element has an `autocomplete` attribute that's currently set to `off`. I don't see any documentation on this attribute; do I perhaps need to set it to `on`? I tried doing that manually with Chrome developer tools and it didn't seem to help, but just thought I'd ask.

**Comment by hammer** [comment]
Okay strangely after a reload this is actually working now! The styling is not great as the search result text is cut off at the sidebar. If anyone with frontend skills sees this issue, I'd love your assistance making this look good...

**Comment by choldgraf** [comment]
@hammer - did you ever get this one working? I agree it would be excellent to document this pattern. If there is some CSS tweaks we can make to improve the algolia search UI, then I'd be +1 on adding those in this theme.

**Comment by dylanh724** [comment]
@hammer Hey bud, your pull request is closed and this is from 2021 -- how did you get this working? Did you ever get it styled? Does anyone have any advice here?

**Comment by dylanh724** [comment]
Hi @gregcaporaso , @rowanc1 , apologies I'm not quite sure who to ping for this -- do you guys know anything about this? I noticed this issue was opened in 2021, so I'm not quite sure if I should bump this (since it's still open) or create a new issue.

**Comment by gregcaporaso** [comment]
@dylanh724, I'm sorry, I don't know anything about this one. Weirdly it looks like there are no pull requests (at all) associated with that repo now. 

I suspect we should close this one with a note to reopen if it becomes relevant again.

**Comment by dylanh724** [comment]
I got it working. I ended up using a custom button to not have to worry about moving/rethemeing the Algolia one since book's is pretty cool and nicely positioned. I'd love to see official integration so we can remove some of our bloat :) Here's to get someone started:

---

## Algolia Sphinx Setup Guide

Follow this normally. Then, override some stuff:

## Conf.py

```py
html_css_files = []
html_css_files.append("styles/css/algoliaDocSearchSphinxBookThemeSupport.css")

## OPTIONAL: Uncomment if you want to use the theme's button instead of Algolia's
#html_js_files = []
#html_js_files.append(("js/customAlgoliaDocSearchBtn.js", {"defer": "defer"}))

# sphinx-book-theme doesn't contain the expected dev, so we inject it in via j2 template
docsearch_container = "#search-input" 

# ⚠️ Yours may look different, but minimally add "inject-algolia-docsearch.j2"
# I like to position it below the "search-button-field"
html_sidebars = {
    "**": [
        "navbar-logo",
        "search-button-field",
        "inject-algolia-docsearch.j2",  # <<<<
        "sbt-sidebar-nav",
    ],
}
```

## SCSS

This is SCSS, but you can probably run it through an online parser if you wanted the raw CSS:

### Core

```scss
* 
##################################################################################
- You should parse this SCSS to CSS before building
- Initial template suggestion from yafimvo @ 
  https://github.com/jupyter-book/jupyter-book/issues/1324#issuecomment-1512757574 
##################################################################################
*/

/* -- sphinx-book-theme Support --------------------------------------------------------------------- */
/* Hide the old theme's (!Algolia's) search wrapper window when hitting Ctrl+K */
.search-button__wrapper, #search-input {
    display: none !important;
}

/* Make sure Algolia's search container is always on top */
.DocSearch.DocSearch-Container {
    z-index: 10000;
}

dialog#pst-search-dialog {
    /* Hide the sphinx-book-theme dialog that pops up on CTRL+K */
    display: none;

    &[hidden] {
        /* Handle sphinx-book-theme's dialog that still pops up on CTRL+K: Hide + prevent interaction */
        pointer-events: none;
        visibility: hidden;
    }
}

### OPTIONAL: Custom Button (Use Theme's)

Did you uncomment that `conf.py` js file earlier to use Book theme's button, instead? Add this to your [S]CSS:

```scss
/* -- Custom search bar (use Theme's search bar): Hide Algolia's ------------------------------------ */
/* This custom search bar pairs heavily with `../_static/js/customAlgoliaDocSearchBtn.js` that redirects clicks */

.sidebar-primary-item:has(#docsearch) {
    display:none
}
```

### OPTIONAL: Narrow Screen Search Bar Workarounds

This is actually an **independent theme bug where the search bar poofs when the screen is narrow enough** - it shouldn't hide the search bar, but since it's related, let's resolve it here before we open a new ticket. 

> **TODO:** Convert this section into an independent issue

```
/* -- General .search-button-field fixes for sphinx-book-theme workarounds -------- */
.sidebar-primary-item {
    /* Fix theme search button field for narrow screens */
    .search-button-field {
        display: flex; /* Align children horizontally */
        justify-content: space-between; /* Space between icon, text, and shortcut */
        align-items: center; /* Vertically */
        width: 100%; /* Ensure it spans the full width; TODO: necessary? */

        /* Undo the display:none and text oddities for narrow screens */
        .search-button__default-text {
            display: unset;
            flex-grow: 1; /* Allow text to take up the remaining space */
            text-align: left;
            font-size: 14px;
        }

        /* CTRL+K text is hidden on narrow screens */
        .search-button__kbd-shortcut {
            display: unset;
        }
    }
}
```
## _templates/inject-algolia-docsearch.j2

Remember in `conf.py`, we included this? All we're doing is injecting an empty `#docsearch` div:

```j2
<!-- Algolia DocSearch requires a #docsearch id wrapper [anywhere] to inject the search bar -->
<!-- This would normally create a search bar, but we'll hide it with CSS, styling our theme's bar -->
<!-- (!) Note `../_sass/algoliaDocSearchSphinxBookThemeSupport.scss` -->
<!-- (!) Note `../_static/js/customAlgoliaDocSearchBtn.js` -->
<div id="docsearch"></div>
```

## OPTIONAL: Use the theme's button instead of Algolia's

### Prereqs (All Stated Above)

1. You uncommented the `conf.py` js line
2. You added the optional css rule to hide Algolia's search bar

### Code

```js
// #########################################
// _static/js/customAlgoliaDocSearchBtn.js
// - Enhances search button functionality to close sidebar and focus search input.
// #########################################

// Selectors
const SEARCH_BUTTON_SELECTOR = '.search-button__button';
const SIDEBAR_DIALOG_SELECTOR = 'dialog#pst-primary-sidebar-modal';
const SEARCH_INPUT_SELECTOR = 'input#DocSearch-Input';

// Initialize the script
const initializeSearchButton = () => {
	const searchButtons = document.querySelectorAll(SEARCH_BUTTON_SELECTOR);

	searchButtons.forEach(button => {
		button.addEventListener('click', handleSearchButtonClick);
	});

	// Add global listener for CTRL+K
	document.addEventListener('keydown', handleCtrlKKeypress);

	console.log('[js/customAlgoliaDocSearchBtn.js] Search buttons and global CTRL+K listener initialized');
};

// Handle the search button click
const handleSearchButtonClick = () => {
	console.log('[js/customAlgoliaDocSearchBtn.js] Search button clicked');

	closeSidebarDialog();
	emulateCtrlKTriggerSearchOverlay();
	focusSearchInput();
};

// Handle CTRL+K keypress
const handleCtrlKKeypress = (event) => {
	if (event.key === 'k' && event.ctrlKey) {
		console.log('[js/customAlgoliaDocSearchBtn.js] CTRL+K pressed');
		closeSidebarDialog(); // Close the sidebar if open
		// Let the default Algolia logic for CTRL+K handle the rest
	}
};

// Close the sidebar dialog if open
const closeSidebarDialog = () => {
	const sidebarDialog = document.querySelector(SIDEBAR_DIALOG_SELECTOR);
	if (sidebarDialog?.open) {
		console.log('[js/customAlgoliaDocSearchBtn.js] Closing sidebar dialog');
		sidebarDialog.close();
	} else {
		console.log('[js/customAlgoliaDocSearchBtn.js] Sidebar dialog not open or not found');
	}
};

// Emulate CTRL+K to trigger the search overlay
const emulateCtrlKTriggerSearchOverlay = () => {
	console.log('[js/customAlgoliaDocSearchBtn.js] emulateCtrlKTriggerSearchOverlay');
	const event = new KeyboardEvent('keydown', {
		key: 'k',
		ctrlKey: true,
		bubbles: true
	});
	focusSearchInput();
	document.dispatchEvent(event);
};

// Focus the search input after a short delay
const focusSearchInput = () => {
	setTimeout(() => {
		const searchInput = document.querySelector(SEARCH_INPUT_SELECTOR);
		if (searchInput) {
			console.log('[js/customAlgoliaDocSearchBtn.js] focusSearchInput');
			searchInput.focus();
		} else {
			console.log(`[js/customAlgoliaDocSearchBtn.js] Search input ${SEARCH_INPUT_SELECTOR} not found`);
		}
	}, 100); // Adjust the delay if necessary
};

// Run the initialization
initializeSearchButton();
```

## Source Available

There's a source-available example from the production site here: https://docs.goxbe.io/ -- See `dev` branch for recent/prettier updates.

Hope this helps someone that can glue this all together minimally.
