### ISSUE TITLE
Allow page-level over-riding of launch button functionality

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/sphinx-book-theme#587]
### Context

Currently, our launch buttons are configured at the documentation-level. The GitHub repository etc are defined in `conf.py` and then used in each page.

However, there are some cases where users might want to specify *per-page Binder configuration*. For example, if a book has notebooks that require many different packages / languages / etc, the author might prefer to define a Binder environment for each in a different branch (or, multiple repositories), and then create different Binder links on each. (cc @Acocac)

### Proposal

We could make it possible to define page-level over-rides for launch buttons. For example, here might be two page-level over-rides, and each would over-ride the corresponding fields in the docs-level `launch:` configuration.

```yaml
launch:
  repository_url: https://github.com/foo/bar
  branch: foo
```

and on another page:

```yaml
launch:
  repository_url: https://github.com/foo/bar
  branch: bar
```

It might be tricky to get the UX right on this, because people probably _won't_ want to duplicate their _content_, only the environment needed to run that content. So I think this might also depend on:

- https://github.com/executablebooks/sphinx-book-theme/issues/282
