### ISSUE TITLE
Header icon_links show in separate rows

### ISSUE THREAD

**Issue by dylanh724** [executablebooks/sphinx-book-theme#879]
This was great for a while -- but it no longer works (not sure when it broke. The latest `1.1.3` has this issue in both Sphinx 7 and 8). Seems that it has to do with `.article-header-buttons` class that's showing on separate rows.

___

![image](https://github.com/user-attachments/assets/1ff15f61-f28a-4381-8a75-0c7a96046ddf)
^ The order gets jumbled if I add even 1 `icon_links`

```py
    "icon_links": [
        {
            "name": "API Docs",
            "url": (
                    "https://foo.com"
            ),
            "icon": "fa-solid fa-book-open",
            "attributes": {"target": "_self"},
        },
        {
            "name": "Discord",
            "url": "https://discord.gg/foo",
            "icon": "fa-brands fa-discord",
            "attributes": {"target": "_blank"},
        },
    ],
```

_Originally posted by @dylanh724 in https://github.com/executablebooks/sphinx-book-theme/issues/833#issuecomment-2497911154_

**Comment by dylanh724** [comment]
Yep, that was it!
![image](https://github.com/user-attachments/assets/9e46f8b3-300d-47f9-8e5a-b11f2aee56b4)

I added this to my arbitrary .css and it's back!

**Comment by dylanh724** [comment]
Please keep this issue open, as I'm pretty curious how this could've happened. I even checked out an old tag -> built -> and it had these issues using the same ver. It was as an update was force-pushed in.

Additionally, I'm having other random CSS issues such as font-weight and a couple others that I suspect is due to the same source cause, but I can't explain it.

**Comment by dylanh724** [comment]
Another noticeable change is this one with the 3rd-column: The vert space is larger

![chrome_r3m8wmPBIM](https://github.com/user-attachments/assets/77017b9a-cb69-4802-865f-91a3df24b2b7)

![image](https://github.com/user-attachments/assets/76007d2c-4752-444b-bf26-96bdc1e0490e)

If I inspect the element and snag a value, I can find it here at _toc_inpage.scss

**Comment by dylanh724** [comment]
Adding
```
h3 {
    font-size: 125%;
    font-weight: normal;
}
```
worked around the other issue.

**Comment by dylanh724** [comment]
> Do you mind writing here exactly what you added to your CSS styles pls?

For the icons:

https://github.com/executablebooks/sphinx-book-theme/issues/879#issuecomment-2497991793

For the font weight:

https://github.com/executablebooks/sphinx-book-theme/issues/879#issuecomment-2498048554

I didn't get to the vertically stretched 3rd column text

**Comment by dylanh724** [comment]
Worked around the 3rd column vertical stretching, too. Here's everything combined:

```css
/* 
SPHINX-BOOK-THEME HOTFIX (top-right icons): 
https://github.com/executablebooks/sphinx-book-theme/issues/879 
*/
.header-article__inner .header-article-items__end, .header-article__inner .header-article-items__start {
    align-items: start;
    display: flex;
    gap: .5rem;
}

/* 
SPHINX-BOOK-THEME HOTFIX (right column vertical stretching fix): 
https://github.com/executablebooks/sphinx-book-theme/issues/879 
*/
.toc-entry a.nav-link {
    padding: .125rem 0 .125rem 1rem;
}

/* 
h3 font weight fix (from extra heavy to normal):
https://github.com/executablebooks/sphinx-book-theme/issues/879 
*/
h3 {
    font-size: 125%;
    font-weight: normal;
}
```
