### ISSUE TITLE
Admonitions: why icons after not before?

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/sphinx-book-theme#96]
Is there a reasoning for this? Don't know if I like it 😬 

<img width="402" alt="image" src="https://user-images.githubusercontent.com/2997570/82380031-c059dd80-9a1f-11ea-881a-6cb0287ae710.png">

I say this because I've been playing around with overriding the RTD theme admonition icon with custom ones for different semantic content e.g.

```css
.title-icon-troubleshoot .admonition-title:before {
    margin-right:.5rem;
    content: "\f0ad"  /* wrench */
}
.title-icon-read-more .admonition-title:before {
    margin-right:.5rem;
    content: "\f08e"  /* external-link */
}
```

```rst
.. admonition:: Having problems?
    :class: attention title-icon-troubleshoot

   ...
```

<img width="716" alt="image" src="https://user-images.githubusercontent.com/2997570/82381228-bb962900-9a21-11ea-8396-01da13770e5f.png">

I don't think this would look as nice with icons after.
